export interface PropertyData {
    category: string
    name: string
    price: number
    address: string
    ku: string
    line: string
    nearest_station: string
    walk: string
    bus: string
    land_area: number
    building_area: number
    balcony: string
    structure: string
    year: number
    management_fee: string
    accumulate_fee: string
    accumulate_fee2: string
    stairs: string
    facing: string
    reform: string
    land_right: string
    parking: string
    completion: string
    link: string
    land_area_tsubo: number
    building_area_tsubo: number
    tsubo_tanka: number
  }